### ISSUE TITLE
max duration of 120 minutes for events necessary?

### ISSUE THREAD

**Issue by pintman** [Zverik/schedule-convert#18]
There is a maximum duration of 120 minutes for events. Is there a reason for this?

https://github.com/Zverik/schedule-convert/blob/2ab0f06cdc1e2dee8fc6c4ccf137d7a82b80cb22/schedule_convert/importers/csv.py#L109

**Comment by Zverik** [comment]
Yes, but it's not a hard requirement, can be increased. This test is to filter out bad values, e.g. 24+ hours.

**Comment by pintman** [comment]
I'd like to use the tool for entries that last longer than 120 minutes. 

Would be nice to have an commandline option for this.

**Comment by pintman** [comment]
Looking through you code, I didn't see a way to hand in arguments to importers. Maybe this can be achieved via env variables?!

**Comment by Zverik** [comment]
Increased the duration to 4 hours. Would that be okay?

**Comment by pintman** [comment]
Maybe not. We will use the schedule for talks as well as stands at a fair. The fair will last the whole day therefore 6-8 hourse might the right time for my purpose. :)

**Comment by Zverik** [comment]
Done :)

**Comment by Zverik** [comment]
Done :)

**Comment by pintman** [comment]
Thanks for the fast support. :)
